class ValueError(Exception):
    pass


class AutoincrementTypeError(Exception):
    pass
